# A docker-compose file for running the Archetype system on one computer.

version: '3'

services:
  archetype-db:
    image: kingsdigitallab/archetype-db
    build: ./db
    expose:
      - "5432"
    ports:
      - "15432:5432"
    volumes:
      - archetype-db-volume:/var/lib/postgresql/data

  archetype-image-server:
    image: kingsdigitallab/archetype-image-server
    build: ./image-server
    expose:
      - "9000"
    volumes:
      - archetype-images:/image
      - archetype-logs:/logs

  archetype-backend:
    image: kingsdigitallab/archetype-backend
    build: ./backend-server
    expose:
      - "8090"
    depends_on:
      - "archetype-db"
    volumes:
      - archetype-django:/django
      - archetype-images:/image
      - archetype-logs:/logs

  archetype-webserver:
    image: kingsdigitallab/archetype-webserver
    build: ./webserver
    expose:
      - "80"
    ports:
      - "6080:80"
    depends_on:
      - "archetype-backend"
      - "archetype-image-server"
    volumes:
      - archetype-django:/django
      - archetype-logs:/logs

volumes:
  archetype-db-volume:

  archetype-images:

  archetype-logs:

  archetype-django:

